language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - cd Example && pod install
script: "xcodebuild -workspace HTPressableButton.xcworkspace -scheme HTPressableButton -destination platform='iOS Simulator', name='iPhone 4s', OS='7.1', id='DF1BBEDE-90C5-41D9-A11B-8DA659322101' clean test | xcpretty -c && exit ${PIPESTATUS[0]}"
